// Texts and destinations are kept together to make the next iterations easy.
export const content = {
  names: 'Daniela & Lucas',
  invitation: 'Los invitamos a nuestra boda',
  proposal: '13 de junio, Roma Italia',
  // Date recovered from the original TickCounter widget (UTC−03:00).
  weddingDate: '2027-02-20T19:00:00-03:00',
  countdownTitle: 'Cuenta regresiva',
  countdownCaption: 'Falta menos para celebrarlo juntos',
  storyTitle: 'Nuestra historia tuvo dos comienzos y un mismo destino.',
  story: 'Nos conocimos en 2018, nos reencontramos en 2021 y\ndesde entonces elegimos recorrer la vida juntos.\nY fue frente al Coliseo, donde comenzó el capítulo\nque hoy venimos a celebrar.',
  schedule: [ ['19.00 Hs', 'Inicio evento'], ['19.30 Hs', 'Ceremonia'], ['20.00 Hs', 'Recepción'] ],
  punctuality: 'Se pide puntualidad para el inicio de la ceremonia',
  venue: 'Salón El Molino Calle 137 Nº 2524, Berazategui',
  women: ['Zapatos elegantes y cómodos', 'Vestido / mono cualquier largo'],
  men: ['Traje o blazer', 'Camisa manga larga de vestir', 'Corbata opcional', 'Zapato formal o mocasines'],
  dressNote: 'Evitar tonos blanco, marfil, crema o beige.',
  songTitle: 'Sugerencia de canción',
  songDescription: '¿Cuál es la canción que no puede faltar en la lista de reproducción de la fiesta?',
  albumTitle: 'Compartí tus fotos',
  albumDescription: 'Sube y comparte con nosotros tus registros de fotos/videos en nuestro álbum de matrimonio',
  giftsTitle: 'Lista de regalos',
  giftsDescription: 'El mejor regalo es compartir este día con ustedes, pero si desean colaborar con nuestro próximo destino y las aventuras que nos quedan por recorrer, pueden hacerlo aquí.',
  rsvpTitle: 'Confirma tu asistencia',
  rsvpDescription: 'Prepárate para disfrutar y celebrar con nosotros',
  // Kept as published. This is later than the wedding date; confirm before launch.
  rsvpDeadline: 'Confirmar asistencia antes del 20.12.27',
  closingEyebrow: '7 maravillas 1 hogar y toda una vida por recorrer.',
  closingTitle: 'Gracias por ser parte de este día.',
  closingCaption: '¡Los esperamos!',
  links: {
    maps: 'https://maps.app.goo.gl/Lp1mzxDHRbsYeF6ZA',
    spotify: 'https://open.spotify.com/playlist/1lAVaJByaEptjNBzEjBMW5?si=FtkoBzsMQi6oGLdBZJPPPw',
    album: 'https://photos.app.goo.gl/JkgNDXPtJgyp12Ru7',
    gifts: 'https://docs.google.com/document/d/1TEVPGDCL-aahcCD64M6yWcAg8jxAhsG-_ENzOfdZOVM/edit?usp=sharing',
    rsvp: 'https://docs.google.com/forms/d/e/1FAIpQLSeHMdDLdd7we1D6Vrk04ecb19CdXfBU9w3XQI919XA7NQ_GsA/viewform?usp=header',
    music: 'https://www.youtube-nocookie.com/embed/_QPDBY08Q0A?autoplay=1',
  },
};
